language: python
python:
- '3.4'

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver*.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

install:
  - python setup.py install
  - pip install -r requirements/heroku_requirements.txt

script:
  - pytest --cov=koalixcrm --cov-report xml --cov-report term
  - python-codacy-coverage -r coverage.xml

# Deployment
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY

  app: koalix-crm
  on:
    repo: scaphilo/koalixcrm
  run:
  - "python manage.py collectstatic --settings=projectsettings.settings.heroku_settings --noinput"
  - "python manage.py makemigrations --settings=projectsettings.settings.heroku_settings"
  - "python manage.py migrate --settings=projectsettings.settings.heroku_settings"
  - "echo \"from django.contrib.auth.models import User; User.objects.create_superuser('Admin002', 'admin002@koalixcrm.com', 'admin002');\" | python manage.py shell"