version: '3'

services:  
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  koalixcrm:    
    build: .    
    volumes:
      - .:/app/
      - static-files:/app/projectsettings/static
      - media-files:/app/projectsettings/media
    expose:
      - "8000"
    depends_on:
      - db
    env_file:
      - ./projectsettings/environment/development.env
  webserver:
    build:
      context: .
      dockerfile: ./projectsettings/services/webserver/Dockerfile
    volumes:         
      - static-files:/app/projectsettings/static
      - media-files:/app/projectsettings/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - koalixcrm    
    env_file:
      - ./projectsettings/environment/development.env 

volumes:
  .:
  static-files:
  media-files:
  pgdata: